### ISSUE TITLE
Only private contacts shown in Mac OS X when both private and public contacts exist

### ISSUE THREAD

**Issue by REDLINK** [1afa/sabre-zarafa#20]
I can only access the private contacts in Mac OS X when both private and public contacts exist and define('FOLDER_RENAME_PATTERN', '%p'); is set in config.inc.php. Things work fine when I try it on other platforms, but the Mac OS X Contacts app always seem to use the first contacts folder(?)
Is this a known issue with their implementation maybe? I'm not really impressed by their software anyway, but my boss uses a MacBook... I can provide a debug log if that helps, I see a "Zarafa_CardDav_Backend  - Address books:" message followed by an array that contains references to both the private and public folders but that doesn't really help.

**Comment by rdevroede** [comment]
Issue with OS X Address Book. Closing as Invalid.
