### ISSUE TITLE
VCardProducer mixing VCard versions 3 and 4

### ISSUE THREAD

**Issue by bokxing-it** [1afa/sabre-zarafa#23]
Reported on the [Zarafa forum](https://forums.zarafa.com/showthread.php?6904-SabreDAV-backend-for-Zarafa&p=46847&viewfull=1#post46847):

> [...] but there is one remaining issue with the producer: the EMAIL tag is now a mixup of vcard versions 3.1 and 4.0.
> vcard 3.1 specifies TYPE=INTERNET[,PREF] whereas 4.0 specifes TYPE=INTERNET,PREF=NN - therefore the parser in SOGO connector cannot handle the vcards by default.
>
> I think staying 3.1 compatible should be the default.

Since the VCard version is a config option, the Producer should adhere to it.

**Comment by rdevroede** [comment]
Already fixed, but never closed.
