### ISSUE TITLE
Compatibility with PHP 7 on Ubuntu 16.04 (and kopano core)

### ISSUE THREAD

**Issue by heikobihr** [1afa/sabre-zarafa#27]
sabre-zarafa crashes my apache on ubuntu 16.04 (segmentation fault, signal 11).

Culprit seems to be
`// Disable MAPI exceptions;`
`// we handle errors by checking a function's return status (at least for now):`
`mapi_enable_exceptions(false);`
in server.php.

If I remove this line, sabre-zarafa seems to work on ubuntu 16.04 with kopano core (8.2.0.441) 
(had to change 
`        // Zarafa server location`
`        define ('ZARAFA_SERVER', 'file:///var/run/kopano/server.sock');`
in config.inc.php as well).

From the sources of the php-mapi extension libraries of zarafa and kopano, it looks to me, that disabling mapi exception handling explicitly is not necessary. The function mapi_enable_exceptions(...)  does nothing, if it does not get an exception class as parameter ([see line 7773 and following here](https://stash.kopano.io/users/jvanderwaa/repos/kopanocore/browse/php7-ext/main.cpp)). So removing `mapi_enable_exceptions(false);` from server.php should be OK.

**Comment by rdevroede** [comment]
mapi_enable_exceptions(false) has been commented out after merging https://github.com/1afa/sabre-zarafa/pull/28

Not changing config.inc.php for the time being, as it is still sabre-zarafa, not sabre-kopano.
