### ISSUE TITLE
Contacts imported of VCF files through Mac OS X Contacts.app don't show addresses in Zarafa webapp

### ISSUE THREAD

**Issue by tkosig** [1afa/sabre-zarafa#9]
Im using Contacts.app (v 7.1 (1170)) on Mac OS X 10.8.4 to connect to Zarafa (ZCP 7.1.2-39121) via sabre-zarafa (0.21).

I've successfully set up sabre-zarafa as per instructions. sabre-zarafa is located in the subdirectory 'sabre-zarafa' and not the web root.

I can use Contacts.app to create addressbook entries on Zarafa by dragging cards in Contacts.app onto the CardDAV addressbook.

The created contacts show all information in Contacts.app but when looking at them in the Zarafa webapp the following information is missing:

- address information
- telephone number (cell phone number does show)

I observed that when an address is entered in webapp it will sync okay to Contacts.app but not the other way around.

Here's a test vCard which can be used to reproduce the issues:
BEGIN:VCARD
VERSION:3.0
ITEM1.X-ABLABEL:PROFILE
UID:b068ec40d8
REV:2013-03-19T20:52:21+00:00
PRODID:-//ownCloud//NONSGML Contacts 0.2.4//EN
ITEM1.URL:http\\://www.google.com/profiles/1234567890
TEL:+1 800 888888
FN:TestFirst TestLast
N:TestLast;TestFirst;;;
EMAIL;TYPE=INTERNET:test@test.com
TEL;TYPE=CELL:+1 800 77777777
ADR;TYPE=HOME:;;33 Test Ave;Test District,\nTestCity;;;TestCountry
END:VCARD

**Comment by rdevroede** [comment]
No more replies. Closing as Works-for-me.
